# Generated by Django 6.0.2 on 2026-02-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_id_alter_matchplayer_id_alter_vote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
