# Generated by Django 6.0.2 on 2026-02-21 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_gamelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winning_team',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='team',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
